# Assignment 9 - Data Science in Finance and Insurance
Submission by: Dennis Goldenberg

In [2]:
#import statements
import numpy as np
import pandas as pd;
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.preprocessing import LabelEncoder

In [4]:
#Generate datasaet

#Generate variables
category = pd.Categorical(["C1"] * 4 + ["C2"] * 6)
quality = pd.Categorical(["B"] + ["G"]*3 + ["B"]*2 + ["G"]*4)
temperature = pd.Categorical(["H"] + ["C"] + ["H"]*2 + ["C"]*2 + ["H"]*3 + ["C"])
value = [86, 15, 40, 33, 25, 38, 73, 79, 28, 50]

#Create training set
train_set = pd.DataFrame({"category": category, "quality": quality,\
    "temperature": temperature, "value": value})
train_set

category quality temperature  value
0       C1       B           H     86
1       C1       G           C     15
2       C1       G           H     40
3       C1       G           H     33
4       C2       B           C     25
5       C2       B           C     38
6       C2       G           H     73
7       C2       G           H     79
8       C2       G           H     28
9       C2       G           C     50

In [7]:
#Ordinarily Encode categorical variables
for i in ['category', 'quality', 'temperature']:
    le = LabelEncoder()
    le.fit(train_set[i])
    train_set[i] = le.transform(train_set[i])
train_set

category  quality  temperature  value
0         0        0            1     86
1         0        1            0     15
2         0        1            1     40
3         0        1            1     33
4         1        0            0     25
5         1        0            0     38
6         1        1            1     73
7         1        1            1     79
8         1        1            1     28
9         1        1            0     50

In [8]:
# generate priors
priors = np.asarray([train_set['category'].value_counts()[j] for j in range(2)])/len(train_set)
priors

array([0.4, 0.6])

In [9]:
mb_fit = MultinomialNB().fit(train_set[['quality', 'temperature']], train_set['category'])
probs_mb = mb_fit.predict_proba(train_set[['quality', 'temperature']])

#get likelihoods

In [10]:
gb_fit = GaussianNB().fit(train_set['value'].values.reshape(-1,1), train_set['category'])
probs_gb = gb_fit.predict_proba(train_set['value'].values.reshape(-1,1))

In [11]:
(probs_mb[:, 0]*probs_gb[:,0])

array([0.1756203 , 0.19582729, 0.14732797, 0.15934869, 0.17712192,
       0.14921735, 0.14310048, 0.15145837, 0.17059751, 0.12769099])

array([0.56211362, 0.49770197, 0.63125211, 0.60157132, 0.55719521,
       0.62695662, 0.64169037, 0.62105358, 0.57379647, 0.68696948])

array([0.43854012, 0.49588069, 0.36847762, 0.39839441, 0.44280479,
       0.37304338, 0.35795109, 0.37875974, 0.42637002, 0.31726141])